export const types = {
  ADD_CONTACTS: 'ADD_CONTACTS',
  SET_CONTACTS: 'SET_CONTACTS',
  DELETE_CONTACT: 'DELETE_CONTACT',
  FILTER_CONTACTS: 'FILTER_CONTACTS',
  FETCH_START: 'FETCH_START',
  FETCH_FINISH: 'FETCH_FINISH',
  FETCH_ERROR: 'FETCH_ERROR',
  FETCH_ERROR_CLEAN: 'FETCH_ERROR_CLEAN',
};
