/* export const ADD_CONTACTS = 'ADD_CONTACTS';
export const SET_CONTACTS = 'SET_CONTACTS';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const FETCH_START = 'FETCH_START';
export const FETCH_FINISH = 'FETCH_FINISH';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_ERROR_CLEAN = 'FETCH_ERROR_CLEAN'; */

/* export const types = {
    ADD_CONTACTS: "ADD_CONTACTS",
    SET_CONTACTS: "SET_CONTACTS",
    DELETE_CONTACT: "DELETE_CONTACT",
    FILTER_CONTACTS: "FILTER_CONTACTS",
    FETCH_START: "FETCH_START",
    FETCH_FINISH: "FETCH_FINISH",
    FETCH_ERROR: "FETCH_ERROR",
    FETCH_ERROR_CLEAN: "FETCH_ERROR_CLEAN",
} */
